import { getCampaigns, seedCampaigns } from "../api";

const initialCampaigns = [
  {
    id: "camp-summer-sale-2025",
    storeId: "seed-store-1",
    isEnabled: true,
    campaignName: "Summer Sale 2025",
    campaignType: "percentage",
    timezone: "UTC",
    campaignSchedule: "scheduled",
    startDateTime: "2025-08-01T00:00",
    endDateTime: "2025-09-01T00:00",
    deliveryMode: "immediate",
    deliveryDays: null,
    expirationMode: "never",
    expirationDays: null,
    expiryTime: null,
    tiers: [],
  },
  {
    id: "camp-welcome-bonus",
    storeId: "seed-store-1",
    isEnabled: true,
    campaignName: "Welcome Bonus",
    campaignType: "number",
    timezone: "UTC",
    campaignSchedule: "scheduled",
    startDateTime: "2025-12-01T00:00",
    endDateTime: "2026-01-01T00:00",
    deliveryMode: "immediate",
    deliveryDays: null,
    expirationMode: "never",
    expirationDays: null,
    expiryTime: null,
    tiers: [],
  },
  {
    id: "camp-holiday-special",
    storeId: "seed-store-1",
    isEnabled: true,
    campaignName: "Holiday Special",
    campaignType: "percentage",
    timezone: "UTC",
    campaignSchedule: "scheduled",
    startDateTime: "2024-12-01T00:00",
    endDateTime: "2025-01-01T00:00",
    deliveryMode: "immediate",
    deliveryDays: null,
    expirationMode: "never",
    expirationDays: null,
    expiryTime: null,
    tiers: [],
  },
  {
    id: "camp-black-friday-deal",
    storeId: "seed-store-1",
    isEnabled: false,
    campaignName: "Black Friday Deal",
    campaignType: "number",
    timezone: "UTC",
    campaignSchedule: "scheduled",
    startDateTime: "2025-11-01T00:00",
    endDateTime: "2025-12-01T00:00",
    deliveryMode: "immediate",
    deliveryDays: null,
    expirationMode: "never",
    expirationDays: null,
    expiryTime: null,
    tiers: [],
  },
];

if (!getCampaigns().length) {
  seedCampaigns(initialCampaigns);
}
